/* Generated By:JavaCC: Do not edit this line. RobotTokenManager.java */
package uniandes.lym.robot.control;
import uniandes.lym.robot.kernel.*;
import uniandes.lym.robot.view.Console;
import java.awt.Point;
import java.io.*;
import java.util.Vector;
import java.util.LinkedList;

/** Token Manager. */
public class RobotTokenManager implements RobotConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x42000080001000L) != 0L)
         {
            jjmatchedKind = 22;
            return 5;
         }
         return -1;
      case 1:
         if ((active0 & 0x2000000001000L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 22;
               jjmatchedPos = 1;
            }
            return 6;
         }
         if ((active0 & 0x40000080000000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 22;
               jjmatchedPos = 0;
            }
            return -1;
         }
         return -1;
      case 2:
         if ((active0 & 0x40000080000000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 22;
               jjmatchedPos = 0;
            }
            return -1;
         }
         if ((active0 & 0x2000000001000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 22;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 3:
         if ((active0 & 0x40000080000000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 22;
               jjmatchedPos = 0;
            }
            return -1;
         }
         if ((active0 & 0x2000000001000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 22;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 4:
         if ((active0 & 0x40000080000000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 22;
               jjmatchedPos = 0;
            }
            return -1;
         }
         if ((active0 & 0x1000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 22;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 5:
         if ((active0 & 0x40000080000000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 22;
               jjmatchedPos = 0;
            }
            return -1;
         }
         if ((active0 & 0x1000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 22;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 6:
         if ((active0 & 0x80000000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 22;
               jjmatchedPos = 0;
            }
            return -1;
         }
         if ((active0 & 0x1000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 22;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 7:
         if ((active0 & 0x80000000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 22;
               jjmatchedPos = 0;
            }
            return -1;
         }
         if ((active0 & 0x1000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 22;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 32:
         jjmatchedKind = 1;
         return jjMoveStringLiteralDfa1_0(0x20000000000000L);
      case 40:
         return jjStopAtPos(0, 16);
      case 41:
         return jjStopAtPos(0, 17);
      case 44:
         return jjStopAtPos(0, 18);
      case 58:
         return jjStopAtPos(0, 61);
      case 59:
         return jjStopAtPos(0, 19);
      case 91:
         return jjStopAtPos(0, 58);
      case 93:
         return jjStopAtPos(0, 60);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa1_0(0x40000080000000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa1_0(0x2000000001000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa1_0(0x3f002000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa1_0(0x200000000000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa1_0(0x10080000000000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa1_0(0x800800800000L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa1_0(0x100000400L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa1_0(0x800L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa1_0(0x20000000000L);
      case 74:
      case 106:
         return jjMoveStringLiteralDfa1_0(0xc000000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa1_0(0x1000000000000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa1_0(0x3200000020L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa1_0(0x4010040000000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa1_0(0x200000000000380L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa1_0(0x80400000000040L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa1_0(0x8000000000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa1_0(0x40400000000L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa1_0(0x100000000000000L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa1_0(0x100000000000L);
      case 124:
         return jjStopAtPos(0, 59);
      default :
         return jjMoveNfa_0(1, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x11200083f801000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x1400000000000L);
      case 70:
      case 102:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStopAtPos(1, 41);
         break;
      case 72:
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x140000002000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x140L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000000L);
      case 79:
      case 111:
         if ((active0 & 0x400L) != 0L)
         {
            jjmatchedKind = 10;
            jjmatchedPos = 1;
         }
         else if ((active0 & 0x200000000000L) != 0L)
            return jjStopAtPos(1, 45);
         return jjMoveStringLiteralDfa2_0(active0, 0x8c013340000a20L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x240800000000000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0xc400000080L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 66:
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000000000000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000800800100L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x20040000000000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000000000L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa3_0(active0, 0x40L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000002000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0xc000000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x3f000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x240800000000000L);
      case 80:
      case 112:
         if ((active0 & 0x200L) != 0L)
            return jjStopAtPos(2, 9);
         else if ((active0 & 0x800L) != 0L)
            return jjStopAtPos(2, 11);
         else if ((active0 & 0x10000000000L) != 0L)
            return jjStopAtPos(2, 40);
         return jjMoveStringLiteralDfa3_0(active0, 0x400000000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x104000400000000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x10080080000000L);
      case 84:
      case 116:
         if ((active0 & 0x80L) != 0L)
            return jjStopAtPos(2, 7);
         else if ((active0 & 0x40000000L) != 0L)
            return jjStopAtPos(2, 30);
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000000000L);
      case 86:
      case 118:
         if ((active0 & 0x20L) != 0L)
         {
            jjmatchedKind = 5;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x3200000000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 67:
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x200000000000000L);
      case 69:
      case 101:
         if ((active0 & 0x200000000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 3;
         }
         else if ((active0 & 0x800000000L) != 0L)
            return jjStopAtPos(3, 35);
         else if ((active0 & 0x80000000000L) != 0L)
            return jjStopAtPos(3, 43);
         return jjMoveStringLiteralDfa4_0(active0, 0x403000000000L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa4_0(active0, 0x40L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x80800000L);
      case 74:
      case 106:
         return jjMoveStringLiteralDfa4_0(active0, 0x28000000L);
      case 75:
      case 107:
         if ((active0 & 0x100L) != 0L)
            return jjStopAtPos(3, 8);
         else if ((active0 & 0x2000000000000L) != 0L)
            return jjStopAtPos(3, 49);
         break;
      case 76:
      case 108:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000001000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa4_0(active0, 0x14000000L);
      case 78:
      case 110:
         if ((active0 & 0x400000000L) != 0L)
            return jjStopAtPos(3, 34);
         else if ((active0 & 0x40000000000L) != 0L)
            return jjStopAtPos(3, 42);
         return jjMoveStringLiteralDfa4_0(active0, 0x800000000000L);
      case 79:
      case 111:
         if ((active0 & 0x100000000L) != 0L)
            return jjStopAtPos(3, 32);
         return jjMoveStringLiteralDfa4_0(active0, 0x80000000000000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0xc003002000L);
      case 83:
      case 115:
         if ((active0 & 0x100000000000000L) != 0L)
            return jjStopAtPos(3, 56);
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000000000L);
      case 84:
      case 116:
         if ((active0 & 0x1000000000000L) != 0L)
            return jjStopAtPos(3, 48);
         else if ((active0 & 0x10000000000000L) != 0L)
            return jjStopAtPos(3, 52);
         return jjMoveStringLiteralDfa4_0(active0, 0xc000000000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x40000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x400000000000L);
      case 69:
      case 101:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStopAtPos(4, 44);
         break;
      case 71:
      case 103:
         return jjMoveStringLiteralDfa5_0(active0, 0x80000000L);
      case 72:
      case 104:
         if ((active0 & 0x4000000000000L) != 0L)
            return jjStopAtPos(4, 50);
         else if ((active0 & 0x8000000000000L) != 0L)
            return jjStopAtPos(4, 51);
         break;
      case 73:
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0xa002000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000000800000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x14001000L);
      case 83:
      case 115:
         if ((active0 & 0x2000L) != 0L)
            return jjStopAtPos(4, 13);
         else if ((active0 & 0x200000000000000L) != 0L)
            return jjStopAtPos(4, 57);
         break;
      case 84:
      case 116:
         if ((active0 & 0x40L) != 0L)
            return jjStopAtPos(4, 6);
         else if ((active0 & 0x800000000000L) != 0L)
            return jjStopAtPos(4, 47);
         else if ((active0 & 0x20000000000000L) != 0L)
            return jjStopAtPos(4, 53);
         return jjMoveStringLiteralDfa5_0(active0, 0x80005000000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x29000000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa6_0(active0, 0x80000000000000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000L);
      case 68:
      case 100:
         if ((active0 & 0x40000000000000L) != 0L)
            return jjStopAtPos(5, 54);
         break;
      case 71:
      case 103:
         if ((active0 & 0x800000L) != 0L)
            return jjStopAtPos(5, 23);
         break;
      case 77:
      case 109:
         return jjMoveStringLiteralDfa6_0(active0, 0x28000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa6_0(active0, 0xa080000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa6_0(active0, 0x5000001000L);
      case 84:
      case 116:
         if ((active0 & 0x1000000L) != 0L)
            return jjStopAtPos(5, 24);
         else if ((active0 & 0x400000000000L) != 0L)
            return jjStopAtPos(5, 46);
         break;
      case 86:
      case 118:
         return jjMoveStringLiteralDfa6_0(active0, 0x14000000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 68:
      case 100:
         return jjMoveStringLiteralDfa7_0(active0, 0xa000000000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa7_0(active0, 0x14000000L);
      case 75:
      case 107:
         if ((active0 & 0x2000000L) != 0L)
            return jjStopAtPos(6, 25);
         break;
      case 78:
      case 110:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa7_0(active0, 0x28000000L);
      case 82:
      case 114:
         if ((active0 & 0x80000000000000L) != 0L)
            return jjStopAtPos(6, 55);
         break;
      case 84:
      case 116:
         return jjMoveStringLiteralDfa7_0(active0, 0x5080000000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 72:
      case 104:
         return jjMoveStringLiteralDfa8_0(active0, 0x5000000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0xa00c000000L);
      case 79:
      case 111:
         if ((active0 & 0x80000000L) != 0L)
            return jjStopAtPos(7, 31);
         break;
      case 83:
      case 115:
         if ((active0 & 0x1000L) != 0L)
            return jjStopAtPos(7, 12);
         break;
      case 84:
      case 116:
         return jjMoveStringLiteralDfa8_0(active0, 0x30000000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStopAtPos(8, 36);
         else if ((active0 & 0x4000000000L) != 0L)
            return jjStopAtPos(8, 38);
         break;
      case 78:
      case 110:
         return jjMoveStringLiteralDfa9_0(active0, 0xc000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0x30000000L);
      case 82:
      case 114:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStopAtPos(8, 37);
         else if ((active0 & 0x8000000000L) != 0L)
            return jjStopAtPos(8, 39);
         break;
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 68:
      case 100:
         return jjMoveStringLiteralDfa10_0(active0, 0xc000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa10_0(active0, 0x30000000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 72:
      case 104:
         return jjMoveStringLiteralDfa11_0(active0, 0x30000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa11_0(active0, 0xc000000L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         if ((active0 & 0x10000000L) != 0L)
            return jjStopAtPos(11, 28);
         else if ((active0 & 0x20000000L) != 0L)
            return jjStopAtPos(11, 29);
         break;
      case 82:
      case 114:
         if ((active0 & 0x4000000L) != 0L)
            return jjStopAtPos(11, 26);
         else if ((active0 & 0x8000000L) != 0L)
            return jjStopAtPos(11, 27);
         break;
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 5;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
               case 0:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 14)
                     kind = 14;
                  jjCheckNAdd(0);
                  break;
               case 6:
               case 2:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 22)
                     kind = 22;
                  jjCheckNAddTwoStates(3, 2);
                  break;
               case 5:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 22)
                     kind = 22;
                  jjCheckNAddTwoStates(3, 2);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((0x600000006L & l) == 0L)
                     break;
                  if (kind > 22)
                     kind = 22;
                  jjCheckNAddTwoStates(2, 4);
                  break;
               case 6:
                  if ((0x600000006L & l) != 0L)
                  {
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(0, 2);
                  }
                  if ((0x600000006L & l) != 0L)
                  {
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddTwoStates(3, 2);
                  }
                  break;
               case 5:
               case 4:
                  if ((0x600000006L & l) == 0L)
                     break;
                  if (kind > 22)
                     kind = 22;
                  jjCheckNAddStates(0, 2);
                  break;
               case 3:
                  if ((0x600000006L & l) == 0L)
                     break;
                  if (kind > 22)
                     kind = 22;
                  jjCheckNAddTwoStates(3, 2);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 5 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   3, 2, 4, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, "\50", "\51", "\54", "\73", null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, "\133", "\174", "\135", "\72", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0x3fffffffffcf7fe1L, 
};
static final long[] jjtoSkip = {
   0x1eL, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[5];
private final int[] jjstateSet = new int[10];
protected char curChar;
/** Constructor. */
public RobotTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public RobotTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 5; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 13 && (0x2600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
