/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BALLOONS = 5;
  /** RegularExpression Id. */
  int CHIPS = 6;
  /** RegularExpression Id. */
  int NUM = 7;
  /** RegularExpression Id. */
  int DIGIT = 8;
  /** RegularExpression Id. */
  int VARS = 9;
  /** RegularExpression Id. */
  int PROCS = 10;
  /** RegularExpression Id. */
  int INIT = 11;
  /** RegularExpression Id. */
  int FACING = 12;
  /** RegularExpression Id. */
  int CANPUT = 13;
  /** RegularExpression Id. */
  int CANPICK = 14;
  /** RegularExpression Id. */
  int CANMOVEINDIR = 15;
  /** RegularExpression Id. */
  int CANJUMPINDIR = 16;
  /** RegularExpression Id. */
  int CANMOVETOTHE = 17;
  /** RegularExpression Id. */
  int CANJUMPTOTHE = 18;
  /** RegularExpression Id. */
  int NOT = 19;
  /** RegularExpression Id. */
  int ASSIGNTO = 20;
  /** RegularExpression Id. */
  int GOTO = 21;
  /** RegularExpression Id. */
  int MOVE = 22;
  /** RegularExpression Id. */
  int TURN = 23;
  /** RegularExpression Id. */
  int FACE = 24;
  /** RegularExpression Id. */
  int MOVETOTHE = 25;
  /** RegularExpression Id. */
  int MOVEINDIR = 26;
  /** RegularExpression Id. */
  int JUMPTOTHE = 27;
  /** RegularExpression Id. */
  int JUMPINDIR = 28;
  /** RegularExpression Id. */
  int NOP = 29;
  /** RegularExpression Id. */
  int PUT = 30;
  /** RegularExpression Id. */
  int PICK = 31;
  /** RegularExpression Id. */
  int IF = 32;
  /** RegularExpression Id. */
  int THEN = 33;
  /** RegularExpression Id. */
  int ELSE = 34;
  /** RegularExpression Id. */
  int WHILE = 35;
  /** RegularExpression Id. */
  int DO = 36;
  /** RegularExpression Id. */
  int REPEAT = 37;
  /** RegularExpression Id. */
  int FRONT = 38;
  /** RegularExpression Id. */
  int LEFT = 39;
  /** RegularExpression Id. */
  int RIGHT = 40;
  /** RegularExpression Id. */
  int BACK = 41;
  /** RegularExpression Id. */
  int NORTH = 42;
  /** RegularExpression Id. */
  int SOUTH = 43;
  /** RegularExpression Id. */
  int EAST = 44;
  /** RegularExpression Id. */
  int WEST = 45;
  /** RegularExpression Id. */
  int AROUND = 46;
  /** RegularExpression Id. */
  int MAY = 47;
  /** RegularExpression Id. */
  int MIN = 48;
  /** RegularExpression Id. */
  int NAME = 49;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"BALLOONS\"",
    "\"CHIPS\"",
    "<NUM>",
    "<DIGIT>",
    "\"VARS\"",
    "\"PROCS\"",
    "\"ROBOT_R\"",
    "\"facing\"",
    "\"canput\"",
    "\"canpick\"",
    "\"canmoveindir\"",
    "\"canjumpindir\"",
    "\"canmovetothe\"",
    "\"canjumptothe\"",
    "\"not\"",
    "\"assignto\"",
    "\"goto\"",
    "\"move\"",
    "\"turn\"",
    "\"face\"",
    "\"movetothe\"",
    "\"moveindir\"",
    "\"jumptothe\"",
    "\"jumpindir\"",
    "\"nop\"",
    "\"put\"",
    "\"pick\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"repeat\"",
    "\"front\"",
    "\"left\"",
    "\"right\"",
    "\"back\"",
    "\"north\"",
    "\"south\"",
    "\"east\"",
    "\"west\"",
    "\"around\"",
    "<MAY>",
    "<MIN>",
    "<NAME>",
    "\",\"",
    "\";\"",
    "\"[\"",
    "\"|\"",
    "\"]\"",
    "\":\"",
  };

}
